// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Web_projekat.Migrations
{
    [DbContext(typeof(OrganizacijaDomaContext))]
    [Migration("20220303160141_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KorisniskoIme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Models.ObjekatZaSmestanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("SobaID")
                        .HasColumnType("int");

                    b.Property<int?>("TipID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("SobaID");

                    b.HasIndex("TipID");

                    b.ToTable("ObjektiZaSmestanje");
                });

            modelBuilder.Entity("Models.Predmet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("SmestenID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SmestenID");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("Models.Soba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sobe");
                });

            modelBuilder.Entity("Models.TipObjektaZaSmestanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TipoviObjekataZaSmestanje");
                });

            modelBuilder.Entity("Models.ObjekatZaSmestanje", b =>
                {
                    b.HasOne("Models.Korisnik", "Korisnik")
                        .WithMany("ObjektiZaSmestanje")
                        .HasForeignKey("KorisnikID");

                    b.HasOne("Models.Soba", "Soba")
                        .WithMany("ObjektiZaSmestanje")
                        .HasForeignKey("SobaID");

                    b.HasOne("Models.TipObjektaZaSmestanje", "Tip")
                        .WithMany("ObjektiZaSmestanje")
                        .HasForeignKey("TipID");

                    b.Navigation("Korisnik");

                    b.Navigation("Soba");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("Models.Predmet", b =>
                {
                    b.HasOne("Models.ObjekatZaSmestanje", "Smesten")
                        .WithMany("Predmeti")
                        .HasForeignKey("SmestenID");

                    b.Navigation("Smesten");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Navigation("ObjektiZaSmestanje");
                });

            modelBuilder.Entity("Models.ObjekatZaSmestanje", b =>
                {
                    b.Navigation("Predmeti");
                });

            modelBuilder.Entity("Models.Soba", b =>
                {
                    b.Navigation("ObjektiZaSmestanje");
                });

            modelBuilder.Entity("Models.TipObjektaZaSmestanje", b =>
                {
                    b.Navigation("ObjektiZaSmestanje");
                });
#pragma warning restore 612, 618
        }
    }
}
